export const posts = [
  {
    id: 1,
    username: 'Airbender',
    avatar: 'https://mir-s3-cdn-cf.behance.net/project_modules/1400/a16a5a112835185.601bdb1e4ed07.jpg',
    content: 'A young boy known as the Avatar must master the four elemental powers to save a world at war and fight a ruthless enemy bent on stopping him.',
    image: 'https://www.elleman.vn/app/uploads/2024/03/01/231073/the-than-_elleman-3.jpg',
    likes: 10,
    comments: 5,
    shares: 2,
  },
  {
    id: 2,
    username: 'Avatar',
    avatar: 'https://cdn.kinocheck.com/i/tbqw8eo6dt.jpg',
    content: 'In the breathtaking world of Avatar, the Navi strive to protect their home from human exploitation and uncover the power of nature.',
    image: 'https://media.npr.org/assets/img/2022/12/15/avatar-pic_wide-daa2aafc1807be2063dab09f9d8453667a1b9cf2.jpg',
    likes: 20,
    comments: 15,
    shares: 10,
  },
    {
    id: 3,
    username: 'Superman hate Spider',
    avatar: 'https://pyxis.nymag.com/v1/imgs/013/ead/52795c43a36696b8e623cb076cff8159b8--my-adventures-with-superman-still-1.1x.rsquare.w1400.jpg',
    content: 'As Spider-Man swings through the bustling streets of New York City, he battles villains while balancing his responsibilities as a student and a hero.',
    image: 'https://images.thedirect.com/media/article_full/superman-dc-henry-cavill.jpg',
    likes: 10,
    comments: 5,
    shares: 2,
  },
  {
    id: 4,
    username: 'Thor Lord',
    avatar: 'https://mediaproxy.salon.com/width/1200/https://media2.salon.com/2019/07/thor-ragnarok2.jpg',
    content: 'In Thor, the God of Thunder must reclaim his power and protect Asgard from the dark forces threatening to plunge the universe into chaos.',
    image: 'https://cdn.britannica.com/73/182873-050-E1C686F4/Chris-Hemsworth-Thor-Thor-The-Dark-World.jpg',
    likes: 60,
    comments: 5,
    shares: 2,
  },
];
